<?php
//usertype:
//(1, 'Suadmin'),
//(2, 'Admin Sales'),
//(3, 'Admin Finance'),
//(4, 'Cashier'),
//(5, 'Admin Inventory'),
//(6, 'Admin Pricing'),
//(7, 'Admin Legal')

//user_main_page = main page for redirection
//user_directory = directory name for each user

$config = array("user_main_page" => array("1" => "/admin/dashboard",
                                          "2" => "/admin-sales/dashboard",
                                          "3" => "/admin-finance/dashboard",
                                          "4" => "/cashier/dashboard",
                                          "5" => "/admin-inventory/dashboard",
                                          "6" => "/admin-pricing/dashboard",
                                          "7" => "/admin-legal/dashboard",
                                          "8" => "/admin-collection/dashboard",
                                         ),
                "user_directory" => array("1" => "admin/",
                                          "2" => "admin-sales/",
                                          "3" => "admin-finance/",
                                          "4" => "cashier/",
                                          "5" => "admin-inventory/",
                                          "6" => "admin-pricing/",
                                          "7" => "admin-legal/",
                                          "8" => "admin-collection/",
                                         ),
                "user_menu" => array(  /*Suadmin*/                           "1" => array("master","partnersupport","booking","legal","legalsupport","module_cashier","partner","cashier", "purchase", "cashier", "dashboard", "bookingsuadmin", "userlist", "user", "payment", "unit", "marketinglist", "marketing", "salesapproval", "salesreport", "rsvplist", "account", "stock", "refund","partnersupport","legal","customersupport","partnerapproval","stockavailability", "test","sales","wireframe"),
                                       /*Partner Support*/                   "2" => array("dashboard", "partnersupport", "marketing","partner"),
                                       /*Legal (Partner Side)*/              "3" => array("dashboard","legal","legalsupport"),
                                       /*Legal (Customer Side)*/             "4" => array("dashboard"),
                                       /*Legal Communication*/               "5" => array("dashboard", "module_cashier", "cashier"),
                                       /*Sales*/                             "6" => array("order_step_2","order","new_cuctomer","dashboard","booking","checkinventory","inventory","check", "salessupport","stock","mail_order","inventorymatrix","sales"),
                                       /*Cashier*/                           "7" => array("dashboard","module_cashier", "cashier","booking_event"),
                                       /*Collection*/                        "8" => array("dashboard"),
                                       /*Accounting ( Account Receivable )*/ "9" => array("dashboard","finance","financemanager","purchase"),
                                       /*Accouting ( Account Payable )*/     "10" => array("dashboard"),
                                       /*Business Intelligence*/             "11" => array("dashboard"),
                                       /*CRM Partner Side*/                  "12" => array("dashboard"),
                                       /*CRM Client Side*/                   "13" => array("dashboard","legal","legalsupport"),
                                       /**/                                  "14" => array("dashboard"),
                                        "15" => array("dashboard"),
                                        "16" => array("dashboard"),
                                        "17" => array("dashboard"),
                                        "18" => array("dashboard"),
                                        "19" => array("dashboard"),
                                        "20" => array("dashboard","legal","legalsupport"),
                                        "21" => array("dashboard","eventmanagement","cashier","bookingnow","event_registration","bookinglist","booking"),
                                        "22" => array("dashboard", "partnersupport", "marketing","partner", "partnerapproval"),
                                        "23" => array("dashboard","financemanager","purchase","booking","bookinglist","finance"),
                                        "24" => array("dashboard","checkinventory","inventory","check", "salessupport","stock","mail_order","inventorymatrix"),
                                        "25" => array("dashboard","inventorymatrix"),
                                        "26" => array("dashboard","master")
                ),
);